export const kp_industry: Pick<IndustryCode, "label" | "value">[] = [
  { label: "农、林、牧、渔业", value: "A" },
  { label: "采矿业", value: "B" },
  { label: "制造业", value: "C" },
  { label: "电力、热力、燃气及水生产和供应业", value: "D" },
  { label: "建筑业", value: "E" },
  { label: "批发和零售业", value: "F" },
  { label: "交通运输、仓储和邮政业", value: "G" },
  { label: "住宿和餐饮业", value: "H" },
  { label: "信息传输、软件和信息技术服务业", value: "I" },
  { label: "金融业", value: "J" },
  { label: "房地产业", value: "K" },
  { label: "租赁和商务服务业", value: "L" },
  { label: "科学研究和技术服务业", value: "M" },
  { label: "水利、环境和公共设施管理业", value: "N" },
  { label: "居民服务、修理和其他服务业", value: "O" },
  { label: "教育", value: "P" },
  { label: "卫生和社会工作", value: "Q" },
  { label: "文化、体育和娱乐业", value: "R" },
  { label: "公共管理、社会保障和社会组织", value: "S" },
  { label: "国际组织", value: "T" },
  { label: "保险业", value: "J6800" },
];
