import { BaseEvent } from "../BaseEvent";
import { QXIN_NEW } from "../event.names";
import { MEMORY_DATA } from "../../config";
import { useAxios, createQxinSign, setError } from "../utils";

// const mock = [
//   {
//     name: "上海犇禄企业管理合伙企业（有限合伙）",
//     credit_no: "91310230MAKKYG6GXN",
//     regist_capi: 475.0475,
//     oper_name: "浙江长红健康产业集团有限公司，郭珍珠，褚珠平，平杰，高晓红",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区三星镇北星公路1999号（集中登记地）",
//   },
//   {
//     name: "上海策雾信息科技有限公司",
//     credit_no: "91310230MAKKYFURX0",
//     regist_capi: 500,
//     oper_name: "宋建刚",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新河镇新开河路825号（集中登记地）",
//   },
//   {
//     name: "上海源梅信息科技有限公司",
//     credit_no: "91310230MAKKYFP07B",
//     regist_capi: 500,
//     oper_name: "吴建辉",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新河镇新开河路825号（集中登记地）",
//   },
//   {
//     name: "上海原像橡企业管理有限公司",
//     credit_no: "91310230MAKKYFJC7B",
//     regist_capi: 500,
//     oper_name: "张旭",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新河镇新开河路825号（集中登记地）",
//   },
//   {
//     name: "上海谷啦啦电子商务有限公司",
//     credit_no: "91310230MAKKMGKM2C",
//     regist_capi: 10,
//     oper_name: "舒金铃",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区横沙乡红丰路33号（集中登记地）",
//   },
//   {
//     name: "上海青源禾木企业管理中心（有限合伙）",
//     credit_no: "91310230MAKKMGGL90",
//     regist_capi: 10,
//     oper_name: "李永飞，曹琛",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "-",
//   },
//   {
//     name: "上海数联智慧信息科技有限公司",
//     credit_no: "91310230MAKKMGFJ6Y",
//     regist_capi: 50,
//     oper_name: "李春侠",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新河镇新薇路56号11幢（集中登记地）",
//   },
//   {
//     name: "上海章寻信息科技有限公司",
//     credit_no: "91310230MAKKMGB3X0",
//     regist_capi: 100,
//     oper_name: "章海军",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区东平镇东冉路547号（集中登记地）",
//   },
//   {
//     name: "海曦力场（上海）品牌管理有限公司",
//     credit_no: "91310230MAKK6UW34E",
//     regist_capi: 50,
//     oper_name: "解美灵",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新海镇跃进中路151号5幢（集中登记地）",
//   },
//   {
//     name: "上海轩鑫嘉业汽车有限公司",
//     credit_no: "91310230MAKK6UQK5B",
//     regist_capi: 500,
//     oper_name: "甘小贝",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新海镇跃进中路151号5幢（集中登记地）",
//   },
//   {
//     name: "上海睿界图网络科技有限公司",
//     credit_no: "91310230MAKK6TPK6H",
//     regist_capi: 10,
//     oper_name: "夏建华",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区东平镇东冉路547号（集中登记地）",
//   },
//   {
//     name: "未来种耔（上海）医疗咨询有限公司",
//     credit_no: "91310230MAKJFYY28X",
//     regist_capi: 300,
//     oper_name: "曲翔",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "崇明区",
//     address: "上海市崇明区新海镇跃进中路151号5幢（集中登记地）",
//   },
//   {
//     name: "上海臻盛荣机械科技有限公司",
//     credit_no: "91310120MAKKYHJUXQ",
//     regist_capi: 200,
//     oper_name: "李晨阳",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区南行港路2900号二层（集中登记地）",
//   },
//   {
//     name: "上海小牛看房云科技有限公司奉贤区分公司",
//     credit_no: "91310120MAKKYH7836",
//     regist_capi: "-",
//     oper_name: "陆晶",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区南桥镇解放西路55号、57号",
//   },
//   {
//     name: "上海轩领环境科技有限公司",
//     credit_no: "91310120MAKKYEMEXN",
//     regist_capi: 100,
//     oper_name: "吴圆圆",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区东方美谷大道5666号1幢3层B区（集中登记地）",
//   },
//   {
//     name: "上海宜心轻舍科技有限公司第一分公司",
//     credit_no: "91310120MAKKYEJ49D",
//     regist_capi: "-",
//     oper_name: "范安勇",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区柘林镇迎龙村迎新1216号",
//   },
//   {
//     name: "上海沪腕钟表维修有限公司",
//     credit_no: "91310120MAKKYECE6C",
//     regist_capi: 5,
//     oper_name: "薛海君",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区望园路1698弄12号3幢2层（集中登记地）",
//   },
//   {
//     name: "上海呆一会文化传媒有限公司",
//     credit_no: "91310120MAKKYE3R5H",
//     regist_capi: 50,
//     oper_name: "余潮洋",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区奉城镇爱德路300号1幢（集中登记地）",
//   },
//   {
//     name: "上海西澜品牌管理有限公司",
//     credit_no: "91310120MAKKYDFJ31",
//     regist_capi: 20,
//     oper_name: "金宣琮",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区南亭公路3258号（集中登记地）",
//   },
//   {
//     name: "上海诗之年生物科技有限公司",
//     credit_no: "91310120MAKKYC974F",
//     regist_capi: 10,
//     oper_name: "张衡星",
//     start_date: "2026-08-04",
//     status: "存续",
//     district: "奉贤区",
//     address: "上海市奉贤区东方美谷大道5666号1幢3层B区（集中登记地）",
//   },
//   {
//     name: "北京信福汇物业服务有限公司",
//     credit_no: "91110105MABTHLKX04",
//     regist_capi: 110000,
//     oper_name: "陈桐",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "朝阳区",
//   },
//   {
//     name: "京橙数藏（北京）科技有限公司",
//     credit_no: "91110112MABTHDN40W",
//     regist_capi: 20000,
//     oper_name: "徐卫星",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "通州区",
//   },
//   {
//     name: "北京思灵智能数据科技有限公司",
//     credit_no: "91110105MABT9A3X9Y",
//     regist_capi: 20000,
//     oper_name: "邵文迪",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "朝阳区",
//   },
//   {
//     name: "北京银佳辉煌科技有限公司",
//     credit_no: "91110108MABQJ7UB4B",
//     regist_capi: 10000,
//     oper_name: "郭蕊新",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "海淀区",
//   },
//   {
//     name: "东方至尊（北京）文化传播有限公司",
//     credit_no: "91110107MABTHCWD9M",
//     regist_capi: 10000,
//     oper_name: "耿琪",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "石景山区",
//   },
//   {
//     name: "北京双赢胜安科技有限公司",
//     credit_no: "91110108MABT91PA6X",
//     regist_capi: 10000,
//     oper_name: "高丽丽",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "海淀区",
//   },
//   {
//     name: "九州聚英（北京）旅游开发有限公司",
//     credit_no: "91110111MABRYREE4G",
//     regist_capi: 9000,
//     oper_name: "胡子超",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "房山区",
//   },
//   {
//     name: "北京奥杰环保科技有限公司",
//     credit_no: "91110111MABT93R961",
//     regist_capi: 5000,
//     oper_name: "刘婵",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "房山区",
//   },
//   {
//     name: "北京雪樱科技有限公司",
//     credit_no: "91110114MABTHM4952",
//     regist_capi: 5000,
//     oper_name: "龚雪",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "昌平区",
//   },
//   {
//     name: "北京骐达本美科技有限公司",
//     credit_no: "91110119MABTHBB304",
//     regist_capi: 5000,
//     oper_name: "甄国霖",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "延庆区",
//   },
//   {
//     name: "华东荣耀（北京）电子竞技有限公司",
//     credit_no: "91110108MABTHH651A",
//     regist_capi: 5000,
//     oper_name: "李玉花",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "海淀区",
//   },
//   {
//     name: "北京槿宸科技有限公司",
//     credit_no: "91110114MABRYTE485",
//     regist_capi: 5000,
//     oper_name: "龚雪",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "昌平区",
//   },
//   {
//     name: "北京国创孵链科技管理有限公司",
//     credit_no: "91110108MABRYN5CXQ",
//     regist_capi: 5000,
//     oper_name: "陈静",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "海淀区",
//   },
//   {
//     name: "北京雀铭科技有限公司",
//     credit_no: "91110115MABRYMLN97",
//     regist_capi: 5000,
//     oper_name: "龚雪",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "大兴区",
//   },
//   {
//     name: "大势启航（北京）科技有限公司",
//     credit_no: "91110108MABQLLXC0Q",
//     regist_capi: 5000,
//     oper_name: "李玉勤",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "海淀区",
//   },
//   {
//     name: "北京石谙商贸有限公司",
//     credit_no: "91110107MABTHJED3Y",
//     regist_capi: 5000,
//     oper_name: "梁旭",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "石景山区",
//   },
//   {
//     name: "北京丰泽德晟智能科技有限公司",
//     credit_no: "91110115MABTH9ML2C",
//     regist_capi: 5000,
//     oper_name: "李凯",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "大兴区",
//   },
//   {
//     name: "北京市亿路兴工劳保用品有限公司",
//     credit_no: "91110111MABQLG2YX9",
//     regist_capi: 5000,
//     oper_name: "吕树琴",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "房山区",
//   },
//   {
//     name: "北京雕瓴建筑有限公司",
//     credit_no: "91110115MABRYQF62A",
//     regist_capi: 5000,
//     oper_name: "陈欣",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "大兴区",
//   },
//   {
//     name: "中芮农业（北京）有限公司",
//     credit_no: "91110119MABRYUGQ35",
//     regist_capi: 5000,
//     oper_name: "罗钧文",
//     start_date: "2022-07-04",
//     status: "存续",
//     district: "延庆区",
//   },
// ];

const emitter = async function (values: INewParams) {
  console.log(values, "values");
  const { qxin_appkey = undefined, qxin_secretkey = undefined } = MEMORY_DATA.config;
  const { pageIndex = 1, province_code = undefined, start_date = undefined, industry_code = undefined } = values;
  if (!qxin_appkey || !qxin_secretkey) return setError("请在设置中配置启信宝appkey和secretkey");
  if (!province_code) return setError("请选择省份");
  const skip = (pageIndex - 1) * 20;

  const instance = useAxios({
    appkey: qxin_appkey,
    timestamp: Date.now(),
    sign: createQxinSign(qxin_appkey, qxin_secretkey),
    "Auth-version": "2.0",
  });

  try {
    const res = await instance.get(`https://api.qixin.com/APIService/enterprise/getNewEnt`, {
      params: {
        province_code,
        start_date,
        industry_code,
        skip,
      },
    });

    // const mock_res = {
    //   status: "200",
    //   message: "操作成功",
    //   sign: "927c6b1a406904b45631ef46e5998acd",
    //   data: {
    //     total: 40,
    //     num: 20,
    //     items: mock.slice(skip, skip + 20),
    //   },
    // };
    // return mock_res;
    console.log(res.request.path, "res");
    console.log(JSON.stringify(res.data), "res.data");

    return res.data;
  } catch (err) {
    return setError(JSON.stringify(err));
  }
};

class QxinNew extends BaseEvent {
  constructor() {
    super(QXIN_NEW, emitter);
  }
}

export const qxinNewIns = new QxinNew();
